[package]
name = "git_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.16", features = ["derive"] }
colored = "2.0"
log = "0.4.22"
simple_logger = "5.0.0"
tempfile = "3.12.0"
